import os

# BASE
SECRET_ID = os.getenv("TENCENTCLOUD_SECRET_ID")
SECRET_KEY = os.getenv("TENCENTCLOUD_SECRET_KEY")
REGION = os.getenv("TENCENTCLOUD_REGION", "ap-guangzhou")

# TEO
ZONE_IDS = list({i.strip() for i in os.getenv("TEO_ZONE_IDS", "").split(",") if i.strip()})

# VPC
ADDRESS_TEMPLATE_PREFIX = "TEO-Origin-ACL"
ADDRESS_TEMPLATE_NAME = f"{ADDRESS_TEMPLATE_PREFIX}-{{date}}-{{index}}"
ADDRESS_TEMPLATE_MAX_ITEMS = int(os.getenv("TEO_ADDRESS_TEMPLATE_MAX_ITEMS", "20"))
ADDRESS_TEMPLATE_GROUP_PREFIX = "TEO-Origin-ACL"
ADDRESS_TEMPLATE_GROUP_NAME = f"{ADDRESS_TEMPLATE_GROUP_PREFIX}-{{date}}"

# SECURITY GROUP
SECURITY_GROUP_ID = os.getenv("SECURITY_GROUP_ID")
SECURITY_GROUP_NOTE_PREFIX = "TEO Node"
SECURITY_GROUP_NOTE = f"{SECURITY_GROUP_NOTE_PREFIX} {{date}}"
SECURITY_GROUP_PROTOCOL = os.getenv("SECURITY_GROUP_PROTOCOL", "TCP")
SECURITY_GROUP_PORT = os.getenv("SECURITY_GROUP_PORT", "443")

# QUERY
QUERY_LIMIT = int(os.getenv("QUERY_LIMIT", "20"))
